// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kluska.ApiService.Data;

#nullable disable

namespace KluskaJustExample.ApiService.Migrations
{
    [DbContext(typeof(KluskaDbContext))]
    partial class KluskaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("kluska.WeatherForecast", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecast", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Date = new DateOnly(2024, 9, 1),
                            Summary = "Sunny",
                            TemperatureC = 25
                        },
                        new
                        {
                            Id = 2L,
                            Date = new DateOnly(2024, 9, 2),
                            Summary = "Cloudy",
                            TemperatureC = 18
                        },
                        new
                        {
                            Id = 3L,
                            Date = new DateOnly(2024, 9, 3),
                            Summary = "Partly cloudy",
                            TemperatureC = 22
                        },
                        new
                        {
                            Id = 4L,
                            Date = new DateOnly(2024, 9, 4),
                            Summary = "Rainy",
                            TemperatureC = 15
                        },
                        new
                        {
                            Id = 5L,
                            Date = new DateOnly(2024, 9, 5),
                            Summary = "Hot",
                            TemperatureC = 30
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
